language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

install: pip install coverage coveralls

script: ./runtests.sh

after_success:
  coveralls

notifications:
  email:
    on_success: never
    on_failure: always
