"""Teptools helpers."""
import os
import glob
import configparser


def parse_rcfile(rcfile, section, default):
    """Return the specified section configurations from users rc file."""
    if rcfile is None:
        rcfile = os.path.join(os.path.expanduser('~'), '.teptoolsrc')

    if not os.path.isfile(rcfile):
        return default

    parser = configparser.ConfigParser()
    parser.read(rcfile)
    config = dict(default)

    if section not in parser:
        parser[section] = {}

    # Use the settings from [DEFAULT] when they don't exist within [section]
    # If the settings don't exist in [DEFAULT] then use the ones in default
    for setting in default:
        config[setting] = parser[section].get(setting, default[setting])

        if type(default[setting]) is list:
            config[setting] = [l.strip()
                               for l in config[setting].split(',')]

    return config


def outfiles(args, ext):
    """Return a list of outfiles to be read from arguments.

    Keyword arguments:
    args -- a list of outfiles arguments passed by the user
    ext  -- extension of the file for globbing

    Return:
    outfiles -- a list of 'useful' files based on the following rules:
    - If an output file is not specified, get all *.{ext} files
    - If an argument includes '*' (glob pattern), expand the glob pattern
    - If the list of files includes directory, get all *.{ext} files within
      that directory.
    - Exclude any files generated by HPC
    - Exclude any files with an extension that is obviously not an output file
    """
    # If an output file is not specified, get all *.{ext} files
    if len(args) == 0:
        args = ['*.' + ext]

    # Provide globbing for arguments
    outfiles = []
    for outfile in args:
        if '*' in outfile:
            outfiles.extend(glob.glob(outfile))
        else:
            outfiles.append(outfile)

    # If arguments contains directories, get all *.{ext} from the directories
    i = 0
    while i < len(outfiles):
        if os.path.isdir(outfiles[i]):
            globbed = glob.glob(os.path.join(outfiles[i], '*.' + ext))
            del outfiles[i]
            outfiles[i:i] = globbed
            i += len(globbed)
        else:
            i += 1

    # Exclude any files generated by HPC
    # Exclude any files with extension as one of the programming languages
    excluded_names = ['slurm', 'pbs']
    excluded_ext = ['py', 'sh', 'f90', 'c', 'cpp']
    i = 0
    while i < len(outfiles):
        if (any(outfiles[i].endswith('.' + ext) for ext in excluded_ext) or
                any(name in outfiles[i] for name in excluded_names)):
            del outfiles[i]
        else:
            i += 1

    return outfiles


def create_file(name, ext):
    """Create a new file from a file name. If a file with the same name already
    exists, it will suffix the file name with a new number."""
    index = 0

    while True:
        if index == 0:
            newfile = name + '.' + ext
        else:
            newfile = name + '_' + str(index) + '.' + ext

        if not os.path.isfile(newfile):
            return newfile, open(newfile, 'a')
        else:
            index += 1
